id: "chlo"
name: "Chunk Loader"
description: "Adds a chunk loader to the game that allows you to permanently load chunks!"
author: "2mal3"
version: "v3.0.0"
minecraft: "1.20"

output: "build"

data_pack:
  name: "Chunk-Loader"
  description: "v3.0.0"
  load:
    - "src"
    - pack.png: "pack.png"

resource_pack:
  name: "Chunk-Loader-Resourcepack"
  load:
    - assets: "assets"
    - pack.png: "pack.png"

pipeline:
  - mecha
  - plugins.remove_empty_functions
  - plugins.installation_advancement
require:
  - bolt

meta:
  version: 30000

  installation_advancement:
    icon:
      item: "minecraft:structure_block"
